%YAML:1.0
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.2204460492503131e-16, -1., 0., 1., 2.2204460492503131e-16,
       0., 0., 0., 1. ]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.0000000000000000e-02, -5.9999999999999998e-02,
       1.0000000000000000e-02 ]
