%YAML:1.0
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.5942328773486114e-02, -9.9987084186029263e-01,
       2.0351292016634716e-03, 9.9974794303804226e-01,
       1.5972482669662336e-02, 1.5777521623200924e-02,
       -1.5807989893762975e-02, 1.7830857962318550e-03,
       9.9987345602359201e-01 ]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -1.3988442922766306e-02, -6.9759508958340238e-02,
       -5.3892141087174272e-03 ]
